site_name: 1Remote
site_description: One Remote Access Manager to Rule Them All
site_author: 1Remote Team
copyright: © 1Remote Team 2023

repo_url: https://github.com/1Remote/1Remote
edit_uri: https://github.com/1Remote/1Remote.github.io/edit/main/source/docs

dev_addr: 127.0.0.1:8000

hide:
  #   - navigation
  - toc
theme:
  custom_dir: overrides
  icon:
    logo: material/library-shelves
  favicon: img/logo.png
  logo: img/logo.png
  features:
    # - navigation.expand
    - navigation.instant # now behaves like a Single Page Application
    - navigation.top # Back-to-top button
    - navigation.indexes # documents can be directly attached to sections, which is particularly useful for providing overview pages: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#with-section-index-pages
    - header.autohide
    - navigation.tabs
    # - navigation.tabs.sticky # tab will not auto hide
    - navigation.sections
    - navigation.tracking
  name: material
  # palette:
  #   - scheme: default
  #     toggle:
  #       icon: material/lightbulb-outline
  #       name: Switch to dark mode
  #   - scheme: slate
  #     toggle:
  #       icon: material/lightbulb
  #       name: Switch to light mode

  palette: # https://www.materialpalette.com/colors
    - scheme: default
      #primary: "teal" # comment to replace by /docs/css/extra.css
      accent: red
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    # - scheme: slate
    #   #primary: "teal" # comment to replace by /docs/assets/stylesheets
    #   accent: teal
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode

extra_css:
  - _extra/css/extra.css
  - _extra/css/pdf.css

extra_javascript:
  - _extra/js/jquery-3.6.0.min.js
  - _extra/js/mathjax.js
  - _extra/js/tablesort.js
  - _extra/js/click-image.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

extra:
  url_prefix: !ENV MM_DOCS_URL_PREFIX
  name: 1Remote
  shortname: 1RM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1Remote/

  analytics:
    provider: google
    property: G-3WQM1ZE8WM

# https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
markdown_extensions:
  # PyMdown extensions: https://python-markdown.github.io/extensions
  - toc:
      permalink:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - meta
  - sane_lists
  - tables

  # PyMdown Extensions extensions: https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  # Extra extensions
  - markdown_include.include:
      base_path: inc
  - plantuml_markdown:
      cachedir: __pycache__

plugins:
  - exclude:
      glob: _*.md
  - macros:
      include_dir: inc
  - search:
      language: en # https://squidfunk.github.io/mkdocs-material/usage/#language
  - tags:
      tags_file: tags.md
  - pdf-export:
      verbose: false
      media_type: print
      enabled_if_env: MM_DOCS_ENABLE_PDF_EXPORT
      combined: false
  - print-site: #https://github.com/timvink/mkdocs-print-site-plugin/blob/master/docs/options.md
      add_to_navigation: false
      print_page_title: "Print Site"
      # Banner and cover
      add_print_site_banner: true
      print_site_banner_template: pdf/banner.tpl
      add_cover_page: true
      cover_page_template: pdf/cover_page.tpl
      # Table of contents
      add_table_of_contents: false
      toc_title: Content
      toc_depth: 2
      # Content-related
      add_full_urls: true
      enumerate_headings: false
      enumerate_figures: true
      include_css: false
      enabled: true
      exclude:
nav:
  - Home: index.md
  - Usage:
      - Basic:
          - Quick Start: usage/quick-start.md
          - Overview: usage/overview.md
          - Launcher:
              - Basic: usage/launcher/basic.md
              - Quick connect: usage/launcher/quick-connect.md
      - Alternative-Credential: usage/alternative-credential.md
      - Database & Security:
          - Security: usage/database/security.md
          - Data synchronization: usage/database/data-synchronization.md
          - Use online database: usage/database/use-online-database.md
      - Protocol:
          - Especial:
              - App: usage/protocol/especial/app.md
              - RemoteApp: usage/protocol/especial/remoteapp.md
              - Rdp in mstsc.exe mode: usage/protocol/especial/rdp-in-mstsc-mode.md
          - Runner: usage/protocol/runner.md
      - Team (experimental):
          - Team sharing: usage/team/team-sharing.md
          - Team deploy: usage/team/team-deploy.md
      - Misc:
          - Highline a server: usage/misc/highline-a-server.md
          - Pre-open a VPN: usage/misc/open-a-vpn-before-connect.md
          - Note for servers: usage/misc/note-for-servers.md
          - Help translation: usage/misc/help-translation.md
            #   - Customized: usage/misc/customized.md
  - Pricing: pricing.md
  - Download: download.md
  - Privacy Policy: privacy-policy.md
  - About: about.md
